---
- name: Generating temporary filename via mktemp
  tags: epel
  command: |
    mktemp -u --suffix .rpm
  register: epel_mktemp

- name: Downloading package to temporary location
  tags: epel
  get_url:
    dest: "{{ epel_mktemp.stdout }}"
    url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ epel_dist }}.noarch.rpm"
  register: epel_get_url
  when: epel_mktemp|success

- name: Ensure that the epel-release package is installed
  tags: epel
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: epel_yum
  with_items: "{{ epel_mktemp.stdout }}"
  when: epel_get_url|success

- name: Applying epel.repo and epel-testing.repo configurations
  tags: epel
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: epel.repo.j2, dst: /etc/yum.repos.d/epel.repo }
    - { src: epel-testing.repo.j2, dst: /etc/yum.repos.d/epel-testing.repo }
  when: epel_yum|success

- name: Ensure that the EPEL GPG keys are installed
  tags: epel
  become: true
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ epel_rel }}"
    state: present
  when: epel_yum|success

- name: Ensure that the required epel packages are installed
  tags: epel
  become: true
  yum:
    disablerepo: "{{ epel_disablerepo|join(',') }}"
    enablerepo: "{{ epel_enablerepo|join(',') }}"
    name: "{{ item }}"
    state: present
  with_items: "{{ epel_packages }}"
  when: epel_packages|length > 0

- name: Purging temporary package from filesystem
  tags: epel
  file:
    path: "{{ epel_mktemp.stdout }}"
    state: absent
  when:
    - epel_mktemp|success
    - epel_yum|success
...
