---
- name: Attempting to generate temporary file
  tags: epel
  tempfile:
    prefix: epel.
    state: file
    suffix: .rpm
  register: epel_tempfile

- name: Attempting to download package to temporary location
  tags: epel
  get_url:
    dest: "{{ epel_tempfile.path }}"
    force: yes
    url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ epel_dist }}.noarch.rpm"
  register: epel_get_url
  when: epel_tempfile is success

- name: Ensure that the epel-release package is installed
  tags: epel
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: epel_yum
  with_items: "{{ epel_tempfile.path }}"
  when: epel_get_url is success

- name: Attempting to purge temporary package from the filesystem
  tags: epel
  file:
    path: "{{ epel_tempfile.path }}"
    state: absent
  when:
    - epel_tempfile is success
    - epel_yum is success

- name: Attempting to overlay epel repository configurations
  tags: epel
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: epel.repo.j2, dst: /etc/yum.repos.d/epel.repo }
    - { src: epel-testing.repo.j2, dst: /etc/yum.repos.d/epel-testing.repo }
  when: epel_yum is success

- name: Ensure that the epel gpg keys are installed
  tags: epel
  become: true
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ epel_dist }}"
    state: present
  when: epel_yum is success

- name: Ensure that the required epel packages are installed
  tags: epel
  become: true
  yum:
    disablerepo: "{{ epel_disablerepo|join(',') }}"
    enablerepo: "{{ epel_enablerepo|join(',') }}"
    name: "{{ item }}"
    state: present
  with_items: "{{ epel_packages }}"
  when:
    - epel_packages|length > 0
    - epel_yum is success
...
