---
- name: Assert that the prerequisites are defined
  tags: epel
  assert:
    that:
      - epel_pkg is defined
      - epel_ver is defined
      - epel_rel is defined
      - epel_baseurl is defined

- name: Acquiring the EPEL GPG Key
  become: true
  rpm_key:
    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ epel_rel }}"
    state: present

- name: Generating temporary filename via mktemp
  tags: epel
  command: mktemp -u --suffix .rpm
  register: epel_mktemp

- name: Downloading package to temporary location
  tags: epel
  get_url:
    url: "{{ epel_fetch }}"
    dest: "{{ epel_mktemp.stdout }}"
  register: epel_get_url
  when: epel_mktemp|success

- name: Ensure that the epel-release package is installed
  tags: epel
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: epel_yum
  with_items: "{{ epel_mktemp.stdout }}"
  when: epel_get_url|success

- name: Applying epel.repo and epel-testing.repo configurations
  tags: epel
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: epel.repo.j2, dst: /etc/yum.repos.d/epel.repo }
    - { src: epel-testing.repo.j2, dst: /etc/yum.repos.d/epel-testing.repo }
  when: epel_yum|success

- name: Purging temporary package from filesystem
  tags: epel
  file:
    path: "{{ epel_mktemp.stdout }}"
    state: absent
  when:
    - epel_mktemp|success
    - epel_yum|success
...
